### ISSUE TITLE
Will be camera issues fixed? 

### ISSUE THREAD

**Issue by jfernandz** [JonnyXDA/android_device_ulefone_metal#10]
I would like to know if camera issues will be fixed in a future, it's a driver issue? or just is Android 7.1.1 app camera?

**Comment by JonnyVR1** [comment]
If the developer who fixed it releases the fix in the open then yes, I will also include this fix in my builds. otherwise my advice is to use a 3rd party camera like Camu that uses it's own video codecs to fix this issue.

**Comment by jfernandz** [comment]
But even using Camu ... The camera is not working so well ... 

I would say ... it's enough but is not working as should be.

**Comment by JonnyVR1** [comment]
Actually I tested it before recommending it and it does work well so as far as I'm concerned this issue is closed.

**Comment by jfernandz** [comment]
When I try to take a picture after record a video Camu fails, so something is not working well with camera, in my case at least. And ... Who do you refer with developer? 

Thank you again :)

**Comment by JonnyVR1** [comment]
In this case please message the developer of Camu.
